---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "",
  fig.path = "README-"
)

library("methexp")
library("data.tree")

# Adapted from https://stackoverflow.com/questions/14188197/representing-a-directory-tree-as-a-recursive-list
tree_list <- function(x) {
  if(grepl("/packrat$", x)) return(list(" ..." = list()))
  if(grepl("/\\.git$", x)) return(list(" ..." = list()))

  isdir <- file.info(x)$isdir
  
  if(!isdir) {
    out <- list()
  } else {
    files <- list.files(
      x
      , full.names   = TRUE
      , include.dirs = FALSE
      , all.files = TRUE
    )
    
    dirs <- list.dirs(
      x
      , full.names   = TRUE
      , recursive = FALSE
    )
    files <- files[!files %in% dirs]
    
    files <- c(
      dirs[!grepl("^\\.", basename(dirs))]
      , dirs[grepl("^\\.", basename(dirs))]
      , files[!grepl("^\\.", basename(files))]
      , files[grepl("^\\.", basename(files))]
    )
    
    files <- files[!grepl("\\.$", files)]
    if(length(files) > 0) {
      out <- lapply(files, tree_list)
      isdir <- sapply(files, function(x) file.info(x)$isdir)
      names(out) <- basename(files)
      names(out)[isdir] <- paste0(names(out)[isdir], "/")
    } else {
      out <- list(NULL)
      names(out) <- paste0(basename(files), "/")
    }
  }
  out
}
```

# methexp

`methexp` contains functions for internal use in the Research Methods and Experimental Psychology group.

## Installation

You can install methexp from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("methexp/methexp")
```

## Example

To set up a new project repository using our standard project structure see `init_project()`:

```{r init-project, results = "hide", message = FALSE}
# Set up project structure in temporary directory
tmp_dir <- tempfile("methexp-")

init_project(
  x = "newproject"
  , path = tmp_dir
  , git = TRUE
  , pkg_structure = TRUE
  , packrat = TRUE
  , ci = TRUE
)

project_path <- file.path(tmp_dir, "newproject")

# Start another study
add_study(x = project_path)

# Start new manuscript
add_paper(
  x = project_path
  , shorttitle = "newproject_paper"
)
```

The resulting directory structure is looks like this:

```{r print-directory-structure, echo = FALSE}
project_structure <- tree_list(tmp_dir)
project_structure <- as.Node(project_structure)
print(project_structure$children$`newproject/`)
```

